### ISSUE TITLE
May I ask if it is possible to support MEK of 1.16.5

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery-Mekanism#2]
May I ask if it is possible to support MEK of 1.16.5.
My players and I are looking forward to it very much.

**Comment by Frinn38** [comment]
It's not possible to backport this addon to 1.16.5 because CM doesn't have a proper API for this version.
So supporting Mekanism for CM 1.16.5 would be a lot of work, way more that I'm willing to do for such an old version.
So the answer is no.
